'use strict';
const OWNER='billcox2020-commits',REPO='-vintage-archive',BRANCH='main',API='https://api.github.com';
const VAULT_KEY='all-collector-admin-vault-v1';
const encoder=new TextEncoder(),decoder=new TextDecoder();
const $=s=>document.querySelector(s);
let token='',pending=null,previewUrl='';
function bytesToBase64(bytes){let binary='';for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(binary)}
function base64ToBytes(v){return Uint8Array.from(atob(v),c=>c.charCodeAt(0))}
async function passwordKey(password,salt){const material=await crypto.subtle.importKey('raw',encoder.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function readVault(password){const vault=JSON.parse(localStorage.getItem(VAULT_KEY)||'null');if(!vault||vault.version!==1)throw new Error('저장된 로그인을 찾지 못했습니다.');const key=await passwordKey(password,base64ToBytes(vault.salt));const out=await crypto.subtle.decrypt({name:'AES-GCM',iv:base64ToBytes(vault.iv)},key,base64ToBytes(vault.cipher));return decoder.decode(out)}
function api(path,options={}){return fetch(`${API}${path}`,{...options,headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28',...(options.headers||{})}}).then(async r=>{if(r.ok)return r.status===204?null:r.json();let m=`GitHub 요청 실패 (${r.status})`;try{const b=await r.json();if(b.message)m=b.message}catch{}throw new Error(m)})}
async function connect(t){token=t.trim();if(!token)throw new Error('토큰을 입력해 주세요.');const me=await api('/user');$('#connectionState').textContent=`연결됨 · ${me.login}`;$('#loginPanel').hidden=true;$('#workspace').hidden=false}
function loginError(e){$('#loginError').textContent=e.message||String(e)}
$('#connectButton').addEventListener('click',()=>connect($('#tokenInput').value).catch(loginError));
$('#unlockButton').addEventListener('click',async()=>{try{await connect(await readVault($('#unlockPassword').value))}catch(e){loginError(e)}});
$('#useTokenButton').addEventListener('click',()=>{$('#passwordLogin').hidden=true;$('#tokenLogin').hidden=false;$('#loginError').textContent=''});
if(localStorage.getItem(VAULT_KEY)){$('#passwordLogin').hidden=false;$('#tokenLogin').hidden=true}
async function imageToJpeg(file){if(file.size>35*1024*1024)throw new Error('사진은 35MB 이하로 선택해 주세요.');const url=URL.createObjectURL(file);try{const img=new Image();await new Promise((ok,no)=>{img.onload=ok;img.onerror=()=>no(new Error('사진을 읽을 수 없습니다.'));img.src=url});const max=3000,scale=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight));const c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.naturalWidth*scale));c.height=Math.max(1,Math.round(img.naturalHeight*scale));const x=c.getContext('2d',{alpha:false});x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.drawImage(img,0,0,c.width,c.height);const blob=await new Promise(ok=>c.toBlob(ok,'image/jpeg',.9));if(!blob)throw new Error('사진 변환에 실패했습니다.');return new Uint8Array(await blob.arrayBuffer())}finally{URL.revokeObjectURL(url)}}
$('#coverFile').addEventListener('change',e=>{pending=e.target.files?.[0]||null;if(previewUrl)URL.revokeObjectURL(previewUrl);if(pending){previewUrl=URL.createObjectURL(pending);$('#coverImage').src=previewUrl;$('#saveButton').disabled=false;$('#saveMessage').textContent='선택 완료. 저장을 누르면 표지가 교체됩니다.'}});
$('#saveButton').addEventListener('click',async()=>{if(!pending||!token)return;const button=$('#saveButton');button.disabled=true;$('#saveMessage').textContent='표지 저장 중…';try{const bytes=await imageToJpeg(pending);const current=await api(`/repos/${OWNER}/${REPO}/contents/assets/archive-room-cover.jpg?ref=${BRANCH}`);await api(`/repos/${OWNER}/${REPO}/contents/assets/archive-room-cover.jpg`,{method:'PUT',body:JSON.stringify({message:'Update archive room cover from admin',content:bytesToBase64(bytes),sha:current.sha,branch:BRANCH})});$('#coverImage').src=`../assets/archive-room-cover.jpg?v=${Date.now()}`;pending=null;$('#coverFile').value='';$('#saveMessage').textContent='완료. 홈페이지 표지가 교체됐습니다.'}catch(e){$('#saveMessage').textContent=e.message||String(e);button.disabled=false}});
